Repository DevCycleHQ/cli, pull requests merged in 2023-06, with the labels that each got.

#138 [fix] select org from flag before prompting projects select
  src/commands/authCommand.ts
  src/commands/login/sso.ts
  src/commands/org/index.ts
  src/commands/projects/select.ts
  src/commands/repo/init.ts
  src/ui/promptForProject.ts
Labels: 1 min review

#139 Use prompted key when clean up aliased variables
  src/commands/cleanup/index.ts
Labels: 1 min review

#141 [feat] add variations list command
  README.md
  docs/variations.md
  oclif.manifest.json
  src/api/variations.ts
  src/commands/variations/list.ts
Labels: 5 min review

#142 Add variations get command
  docs/variations.md
  oclif.manifest.json
  src/commands/variations/get.ts
Labels: 30 min review

#140 DVC-7652 [chore]: update @oclif/core to latest
  docs/help.md
  docs/keys.md
  oclif.manifest.json
  package.json
  src/api/ssoAuth.ts
  src/auth/getToken.ts
  src/commands/alias/add.ts
  src/commands/authCommand.ts
  src/commands/base.ts
  src/commands/cleanup/index.ts
  src/commands/createCommand.ts
  src/commands/diff/index.ts
  src/commands/environments/create.ts
  src/commands/environments/get.ts
  src/commands/environments/list.ts
  src/commands/environments/update.ts
  src/commands/features/get.ts
  src/commands/features/list.ts
  src/commands/generate/types.ts
  src/commands/keys/get.ts
  src/commands/login/again.ts
  src/commands/login/sso.ts
  src/commands/projects/create.ts
  src/commands/projects/list.ts
  src/commands/projects/select.ts
  src/commands/repo/init.ts
  src/commands/updateCommand.ts
  src/commands/variables/create.ts
  src/commands/variables/get.ts
  src/commands/variables/list.ts
  src/commands/variables/update.ts
  src/commands/variations/get.ts
  src/commands/variations/list.ts
  test/commands/diff.test.ts
  test/commands/generate-types.test.ts
  yarn.lock
Labels: 10 min review

#143 DVC-7629 [feat]: add command to get targeting rules for a specific feature
  README.md
  docs/targeting.md
  oclif.manifest.json
  src/api/targeting.ts
  src/commands/targeting/get.ts
Labels: 5 min review

#144 DVC-7630 [feat]: add enable / disable targeting functionality
  README.md
  docs/targeting.md
  oclif.manifest.json
  package.json
  src/api/targeting.ts
  src/commands/targeting/disable.ts
  src/commands/targeting/enable.ts
  src/commands/targeting/get.ts
Labels: 5 min review

#147 DVC-7709 [fix]: generate types command excludes archived variables
  src/api/variables.ts
  test/commands/generate-types.test.ts
Labels: 1 min review

#148 remove the prompt for _feature from environments update
  src/commands/environments/update.ts
Labels: 1 min review

#149 [fix] add dvc-referrer and dvc-metadata properly to cli
  src/api/apiClient.ts
Labels: 1 min review

#151 [fix] terminate command when headless flag is present
  src/commands/diff/index.ts
  src/commands/targeting/get.ts
Labels: 1 min review

#156 chore: change authentication error to tell user to login again
  src/api/apiClient.ts
Labels: 1 min review

#155 fix: Correct environment name
  src/commands/environments/get.ts
  src/commands/environments/update.ts
  src/commands/keys/get.ts
  src/commands/targeting/disable.ts
  src/commands/targeting/enable.ts
  src/ui/prompts/environmentPrompts.ts
  src/ui/prompts/index.ts
Labels: 5 min review

#157 chore: change color gray to dim
  src/ui/prompts/environmentPrompts.ts
  src/ui/writer.ts
Labels: 1 min review

#158 chore: Add variation list tests
  package.json
  src/commands/variations/list.test.ts
  test-utils/dvcTest.ts
  test-utils/index.ts
  tsconfig.json
Labels: 5 min review

#159 chore: collocate tests with commands
  src/commands/cleanup/cleanup.test.ts
  src/commands/diff/diff.test.ts
  src/commands/generate/types.test.ts
  src/commands/usages/usages.test.ts
  src/utils/diff/parse.test.ts
  src/utils/parsers/android/android.test.ts
  src/utils/parsers/csharp/csharp.test.ts
  src/utils/parsers/dart/dart.test.ts
  src/utils/parsers/golang/golang.test.ts
  src/utils/parsers/ios/ios.test.ts
  src/utils/parsers/java/java.test.ts
  src/utils/parsers/javascript/javascript.test.ts
  src/utils/parsers/nodejs/nodejs.test.ts
  src/utils/parsers/php/php.test.ts
  src/utils/parsers/python/python.test.ts
  src/utils/parsers/react/react.test.ts
  src/utils/parsers/ruby/ruby.test.ts
Labels: 5 min review, safe-changes

#162 Use enquirer autocomplete for project select
  src/api/apiClient.ts
  src/api/organizations.ts
  src/ui/promptForProject.ts
Labels: 1 min review

#164 add tests for variable create
  src/commands/variables/create.test.ts
  src/commands/variables/create.ts
  src/ui/prompts/featurePrompts.ts
Labels: 5 min review

#160 feat: List Prompt Option Class
  .eslintrc
  .gitignore
  package.json
  src/api/variables.ts
  src/ui/prompts/listPrompts/listOptionsPrompt.ts
  src/ui/prompts/listPrompts/promptOptions.ts
  src/ui/prompts/listPrompts/variableListPrompts.ts
  src/ui/writer.ts
  yarn.lock
Labels: 5 min review

#167 chore: Add FeaturePromptResult and VariablePromptResult types
  src/commands/cleanup/index.ts
  src/commands/targeting/get.ts
  src/commands/variables/update.ts
  src/ui/prompts/featurePrompts.ts
  src/ui/prompts/variablePrompts.ts
Labels: 1 min review

#163 fix: headless mode being ignored on variable and environment update
  docs/environments.md
  docs/variables.md
  oclif.manifest.json
  src/commands/base.ts
  src/commands/createCommand.ts
  src/commands/environments/create.ts
  src/commands/environments/update.ts
  src/commands/projects/create.ts
  src/commands/updateCommand.ts
  src/commands/variables/create.test.ts
  src/commands/variables/create.ts
  src/commands/variables/update.ts
  src/commands/variations/create.ts
  src/ui/prompts/environmentPrompts.ts
  src/ui/prompts/index.ts
  src/ui/prompts/types.ts
  src/ui/prompts/variablePrompts.ts
  src/utils/prompts.ts
Labels: 10 min review

#168 Add autocomplete to all list prompts
  package.json
  src/commands/cleanup/index.ts
  src/commands/environments/get.ts
  src/commands/environments/update.ts
  src/commands/keys/get.ts
  src/commands/targeting/disable.ts
  src/commands/targeting/enable.ts
  src/commands/targeting/get.ts
  src/commands/variables/update.ts
  src/ui/autocomplete.ts
  src/ui/promptForOrganization.ts
  src/ui/promptForProject.ts
  src/ui/prompts/environmentPrompts.ts
  src/ui/prompts/featurePrompts.ts
  src/ui/prompts/variablePrompts.ts
  yarn.lock
Labels: 5 min review

#166 feat: added create feature command
  .DS_Store
  docs/features.md
  oclif.manifest.json
  src/api/common.ts
  src/api/features.ts
  src/api/variables.ts
  src/auth/getToken.ts
  src/commands/base.ts
  src/commands/createCommand.ts
  src/commands/features/create.test.ts
  src/commands/features/create.ts
  src/commands/variables/create.ts
  src/ui/prompts/featurePrompts.ts
  src/ui/prompts/listPrompts/listOptionsPrompt.ts
  src/ui/prompts/listPrompts/variableListPrompts.ts
  src/ui/prompts/listPrompts/variablesListPrompt.ts
  src/ui/prompts/listPrompts/variationsListPrompt.ts
  src/ui/prompts/variablePrompts.ts
  src/ui/writer.ts
  src/utils/prompts.ts
  src/utils/reportValidationErrors.ts
Labels: 10 min review

#169 feat: added hint text transformer function to show hints when field is empty
  src/commands/createCommand.ts
  src/ui/prompts/commonPrompts.ts
  src/ui/prompts/types.ts
  src/ui/prompts/variablePrompts.ts
Labels: 5 min review

#172 feat: Print targeting rules using Tree when not running headless mode
  package.json
  src/api/apiClient.ts
  src/api/schemas.ts
  src/commands/targeting/__snapshots__/get.test.ts.snap
  src/commands/targeting/get.test.ts
  src/commands/targeting/get.ts
  src/ui/targetingTree.ts
  test-utils/index.ts
  test-utils/setCurrentTestFile.ts
  yarn.lock
Labels: 5 min review

#171 Use zod schema for CreateFeatureDto
  src/api/features.ts
  src/api/schemas.ts
  src/api/zodClient.ts
  src/commands/base.ts
  src/commands/environments/create.ts
  src/commands/environments/update.ts
  src/commands/features/create.test.ts
  src/commands/features/create.ts
Labels: 5 min review

#174 Use zod schema for CreateVariableDto
  src/api/apiClient.ts
  src/api/schemas.ts
  src/api/variables.ts
  src/commands/base.ts
  src/commands/features/create.test.ts
  src/commands/features/create.ts
  src/commands/variables/create.ts
  src/commands/variables/update.ts
  src/ui/prompts/featurePrompts.ts
  src/ui/prompts/listPrompts/listOptionsPrompt.ts
  src/ui/prompts/listPrompts/variablesListPrompt.ts
  src/ui/prompts/variablePrompts.ts
  src/utils/reportValidationErrors.ts
Labels: 5 min review

#175 Use CreateVariationDto from zod
  src/api/schemas.ts
  src/api/variations.ts
  src/commands/variations/create.ts
  src/ui/prompts/listPrompts/variationsListPrompt.ts
Labels: 5 min review

#176 add headless checks to variations get/list
  src/commands/variations/get.ts
  src/commands/variations/list.test.ts
  src/commands/variations/list.ts
Labels: 1 min review

#179 Add features update command
  docs/features.md
  oclif.manifest.json
  src/api/features.ts
  src/api/schemas.ts
  src/commands/base.ts
  src/commands/features/__snapshots__/update.test.ts.snap
  src/commands/features/create.test.ts
  src/commands/features/create.ts
  src/commands/features/update.test.ts
  src/commands/features/update.ts
  src/commands/updateCommand.ts
  src/ui/prompts/commonPrompts.ts
  src/ui/prompts/featurePrompts.ts
  src/ui/prompts/listPrompts/variablesListPrompt.ts
  src/ui/prompts/types.ts
Labels: 10 min review

#181 Prompt for variations in features create / update:
  docs/features.md
  oclif.manifest.json
  src/api/schemas.ts
  src/commands/features/create.test.ts
  src/commands/features/create.ts
  src/commands/features/update.ts
  src/commands/variations/create.ts
  src/commands/variations/update.ts
  src/ui/prompts/commonPrompts.ts
  src/ui/prompts/listPrompts/listOptionsPrompt.ts
  src/ui/prompts/listPrompts/variationsListPrompt.ts
  src/ui/prompts/types.ts
  src/ui/prompts/variablePrompts.ts
  src/ui/prompts/variationPrompts.ts
Labels: 10 min review

#180 feat: add targeting update command
  docs/targeting.md
  oclif.manifest.json
  src/api/schemas.ts
  src/api/targeting.ts
  src/api/zodClient.ts
  src/commands/targeting/__snapshots__/update.test.ts.snap
  src/commands/targeting/update.test.ts
  src/commands/targeting/update.ts
  src/commands/updateCommand.ts
  src/ui/prompts/listPrompts/filterListPrompt.ts
  src/ui/prompts/listPrompts/targetingListPrompt.ts
  src/ui/prompts/listPrompts/variablesListPrompt.ts
  src/ui/prompts/targetingPrompts.ts
  src/ui/prompts/types.ts
  src/ui/prompts/variationPrompts.ts
  src/utils/prompts.ts
Labels: 10 min review

#182 chore: add hint text for variable value type
  src/ui/prompts/variablePrompts.ts
Labels: 1 min review

#184 chore: add variable type as hint text to variations update
  src/ui/prompts/variationPrompts.ts
Labels: 1 min review

#185 chore: move ContinuePrompt be the first one of the list
  src/ui/prompts/listPrompts/filterListPrompt.ts
  src/ui/prompts/listPrompts/listOptionsPrompt.ts
  src/ui/prompts/listPrompts/targetingListPrompt.ts
  src/ui/prompts/listPrompts/variablesListPrompt.ts
  src/ui/prompts/listPrompts/variationsListPrompt.ts
Labels: 1 min review

#188 chore: add AND to targeting tree
  src/ui/targetingTree.ts
Labels: 1 min review

#186 feat: add id field to ListOption
  src/commands/targeting/update.test.ts
  src/ui/prompts/listPrompts/filterListPrompt.ts
  src/ui/prompts/listPrompts/listOptionsPrompt.ts
  src/ui/prompts/listPrompts/targetingListPrompt.ts
  src/ui/prompts/listPrompts/variablesListPrompt.ts
  src/ui/prompts/listPrompts/variationsListPrompt.ts
Labels: 5 min review

#189 feat: made features create command a quick create, added interactive mode
  docs/features.md
  oclif.manifest.json
  src/api/environments.ts
  src/commands/base.ts
  src/commands/environments/create.ts
  src/commands/features/create.test.ts
  src/commands/features/create.ts
  src/commands/features/update.ts
  src/commands/projects/create.ts
  src/commands/variations/create.ts
  src/commands/variations/update.ts
  src/ui/prompts/commonPrompts.ts
  src/ui/prompts/variablePrompts.ts
  src/ui/prompts/variationPrompts.ts
  src/utils/features/quickCreateFeatureUtils.ts
Labels: 10 min review

#191 chore: add colors to the tree
  src/ui/constants/colors.ts
  src/ui/targetingTree.ts
Labels: 5 min review

#193 Dvc 8010 log command suggestion
  src/commands/targeting/__snapshots__/update.test.ts.snap
  src/commands/targeting/update.ts
  src/commands/variations/__snapshots__/update.test.ts.snap
  src/ui/prompts/featurePrompts.ts
  src/ui/prompts/listPrompts/targetingListPrompt.ts
Labels: 1 min review

#194 chore: make server default for sdkVisibility
  src/api/projects.ts
  src/commands/features/create.test.ts
  src/commands/features/create.ts
  src/ui/prompts/featurePrompts.ts
Labels: 5 min review

#197 chore: add suggested command to feature creation
  src/commands/features/create.test.ts
  src/commands/features/create.ts
Labels: 1 min review

#198 feat: Display targeting as tree in update command
  .github/workflows/tests.yml
  package.json
  src/commands/targeting/__snapshots__/update.test.ts.snap
  src/commands/targeting/update.test.ts
  src/commands/targeting/update.ts
  src/ui/prompts/listPrompts/filterListPrompt.ts
  src/ui/prompts/listPrompts/targetingListPrompt.ts
  src/ui/targetingTree.ts
Labels: 5 min review
