Repository DevCycleHQ/cli, pull requests merged in 2023-05, with the labels that each got.

#121 feature: add watch mode to generate types command
  README.md
  docs/generate.md
  oclif.manifest.json
  package.json
  src/api/variables.ts
  src/commands/generate/types.ts
Labels: 5 min review

#126 feature: add variable type generation
  README.md
  docs/generate.md
  oclif.manifest.json
  package.json
  src/api/variables.ts
  src/commands/generate/types.ts
  test/commands/generate-types.test.ts
Labels: 5 min review

#128 DVC-7351 add variableValue() function support to CLI
  src/utils/parsers/android/index.ts
  src/utils/parsers/csharp/index.ts
  src/utils/parsers/dart/index.ts
  src/utils/parsers/golang/index.ts
  src/utils/parsers/ios/index.ts
  src/utils/parsers/java/index.ts
  src/utils/parsers/javascript/index.ts
  src/utils/parsers/nodejs/index.ts
  src/utils/parsers/php/index.ts
  src/utils/parsers/python/index.ts
  src/utils/parsers/ruby/index.ts
  src/utils/refactor/javascript/JavascriptEngine.ts
  test-utils/fixtures/diff/android
  test-utils/fixtures/diff/csharp
  test-utils/fixtures/diff/custom-pattern-value
  test-utils/fixtures/diff/dart
  test-utils/fixtures/diff/golang
  test-utils/fixtures/diff/ios
  test-utils/fixtures/diff/java
  test-utils/fixtures/diff/javascript
  test-utils/fixtures/diff/nodejs
  test-utils/fixtures/diff/optional-accessor
  test-utils/fixtures/diff/php
  test-utils/fixtures/diff/python
  test-utils/fixtures/diff/react
  test-utils/fixtures/diff/ruby
  test/commands/diff.test.ts
  test/diff-parser/parsers/android.test.ts
  test/diff-parser/parsers/csharp.test.ts
  test/diff-parser/parsers/dart.test.ts
  test/diff-parser/parsers/golang.test.ts
  test/diff-parser/parsers/ios.test.ts
  test/diff-parser/parsers/java.test.ts
  test/diff-parser/parsers/javascript.test.ts
  test/diff-parser/parsers/nodejs.test.ts
  test/diff-parser/parsers/php.test.ts
  test/diff-parser/parsers/python.test.ts
  test/diff-parser/parsers/react.test.ts
  test/diff-parser/parsers/ruby.test.ts
Labels: 10 min review

#131 clarify what auth is preferred
  README.md
  oclif.manifest.json
Labels: 1 min review

#132 fix login again command
  src/auth/config.ts
  src/commands/authCommand.ts
  src/commands/base.ts
Labels: 1 min review

#136 Release new
  README.md
  docs/cleanup.md
  docs/diff.md
  docs/logout.md
  docs/org.md
  docs/status.md
  docs/usages.md
  oclif.manifest.json
  package.json
Labels: 5 min review
