Repository DevCycleHQ/cli, pull requests merged in 2023-09, with the labels that each got.

#269 Log error if login port is in use
  src/auth/SSOAuth.ts
Labels: 1 min review

#268 DVC-8630 [feat]: add dvc identity update command
  README.md
  docs/identity.md
  oclif.manifest.json
  src/api/userProfile.ts
  src/api/zodClient.ts
  src/commands/identity/update.ts
  src/ui/prompts/identityPrompts.ts
  src/ui/prompts/index.ts
Labels: 5 min review

#276 DVC-8635 [feat]: add CLI command to clear all overrides for a project
  README.md
  docs/overrides.md
  oclif.manifest.json
  package.json
  src/api/overrides.ts
  src/api/zodClient.ts
  src/commands/identity/update.ts
  src/commands/overrides/clear.ts
Labels: 5 min review

#279 feat: add dvc overrides clear for feature and environment
  docs/overrides.md
  oclif.manifest.json
  src/api/overrides.ts
  src/api/zodClient.ts
  src/commands/overrides/clear.ts
Labels: 5 min review

#280 feat: Update output message when no variables changed in diff
  src/commands/diff/__snapshots__/diff.test.ts.snap
  src/commands/diff/diff.test.ts
  src/commands/diff/index.ts
Labels: 1 min review

#277 DVC-8633: feat: add overrides update
  README.md
  docs/overrides.md
  oclif.manifest.json
  src/api/overrides.ts
  src/api/schemas.ts
  src/api/zodClient.ts
  src/commands/overrides/update.ts
Labels: 5 min review

#281 chore: remove variable feature prompt from create variable prompts, prompt manually in create command
  src/commands/variables/create.test.ts
  src/commands/variables/create.ts
  src/ui/prompts/featurePrompts.ts
  src/ui/prompts/variablePrompts.ts
Labels: 5 min review

#278 overrides get command
  README.md
  docs/overrides.md
  oclif.manifest.json
  src/api/overrides.ts
  src/api/zodClient.ts
  src/commands/overrides/get.ts
Labels: 5 min review

#282 DVC-8696 [feat]: add ability to get all Overrides for a user in a project
  docs/overrides.md
  oclif.manifest.json
  src/api/overrides.ts
  src/api/zodClient.ts
  src/commands/overrides/get.ts
Labels: 5 min review

#285 chore: overrides update command to print results in table
  src/commands/overrides/list.ts
  src/commands/overrides/update.ts
Labels: 1 min review

#286 chore: add repository dispatch step when publishing cli for homebrew tap
  .github/workflows/cli-release.yml
Labels: 1 min review

#284 DVC-8772 chore: filter prompts for overrides
  src/api/overrides.ts
  src/api/zodClient.ts
  src/commands/overrides/clear.ts
  src/commands/overrides/get.ts
  src/ui/prompts/environmentPrompts.ts
  src/ui/prompts/featurePrompts.ts
  src/ui/prompts/overridePrompts.ts
  src/ui/prompts/types.ts
  src/utils/variations/index.ts
Labels: 5 min review

#287 DVC-8827 [fix]: adds defaults sort by feature name then by environment type display order (dev, staging, prod)
  src/commands/overrides/list.ts
  src/utils/environments/index.ts
  src/utils/overrides/index.ts
Labels: 5 min review

#288 Only update selected variation values instead of overriding all
  src/commands/variations/update.test.ts
  src/commands/variations/update.ts
Labels: 1 min review

#289 fix: Update repo init command to not open browser window unless it needs to
  docs/login.md
  docs/organizations.md
  docs/projects.md
  docs/repo.md
  src/commands/authCommand.ts
  src/commands/repo/init.ts
Labels: 5 min review

#290 chore: added gitlab pr insights and code usages as possible caller values
  oclif.manifest.json
Labels: 5 min review

#293 fix: added gitlab pr insights and code usages
  src/commands/base.ts
Labels: 1 min review

#292 chore: Add additional docs on match patterns
  README.md
Labels: 1 min review, safe-changes

#291 feat: add info comments to type generator
  docs/generate.md
  oclif.manifest.json
  src/api/members.ts
  src/commands/generate/types.test.ts
  src/commands/generate/types.ts
Labels: 5 min review

#294 feat: Add handling for gitlab pr links
  src/commands/diff/__snapshots__/diff.test.ts.snap
  src/commands/diff/diff.test.ts
  src/commands/diff/index.ts
Labels: 1 min review

#295 fix: Don't include lines less than 1 in the code snippet buffer
  src/utils/parsers/BaseParser.ts
Labels: 1 min review

#296 Add timeout to sso login
  src/auth/SSOAuth.ts
Labels: 1 min review

#297 feat: add command to display current project
  docs/projects.md
  oclif.manifest.json
  src/commands/base.ts
  src/commands/keys/get.ts
  src/commands/login/again.ts
  src/commands/projects/current.ts
  src/commands/projects/list.ts
  src/commands/status/index.ts
  src/types/configFile.ts
Labels: 5 min review

#298 fix: Clear timeout when sso command completes
  src/auth/SSOAuth.ts
Labels: 1 min review

#299 fix: Set personalAccessToken to be used by sso command
  src/commands/login/sso.ts
Labels: 1 min review

#303 chore: Update min node version to 16.0.0
  package.json
Labels: 1 min review

#302 fix: Don't include variations in feature update if they were not modified
  src/commands/features/update.test.ts
  src/commands/features/update.ts
  src/ui/prompts/commonPrompts.ts
  src/ui/prompts/listPrompts/listOptionsPrompt.ts
  src/ui/prompts/listPrompts/variablesListPrompt.ts
  src/ui/prompts/types.ts
Labels: 1 min review

#305 chore: escape glob patterns for include exclude flags
  .eslintrc
  package.json
  src/commands/cleanup/index.ts
  src/commands/usages/__snapshots__/usages.test.ts.snap
  src/commands/usages/index.ts
  src/commands/usages/usages.test.ts
  test-utils/fixtures/cleanup/javascript/[org_id]/test.js
  test-utils/fixtures/usages/[org_id]/golang.go
  test-utils/fixtures/usages/[org_id]/nodejs.js
  test-utils/fixtures/usages/[org_id]/react.js
  test-utils/fixtures/usages/[org_id]/sample.dart
Labels: 30 min review
