Repository DevCycleHQ/cli, pull requests merged in 2023-07, with the labels that each got.

#199 variations update should now properly accept feature keys as an arg
  src/commands/variations/update.test.ts
  src/commands/variations/update.ts
Labels: 1 min review

#196 chore: add validation to prompts
  src/commands/base.ts
  src/commands/environments/create.ts
  src/commands/environments/update.ts
  src/commands/features/create.ts
  src/commands/features/update.ts
  src/ui/prompts/commonPrompts.ts
  src/ui/prompts/listPrompts/listOptionsPrompt.ts
  src/ui/prompts/listPrompts/targetingListPrompt.ts
  src/ui/prompts/listPrompts/variablesListPrompt.ts
  src/ui/prompts/listPrompts/variationsListPrompt.ts
  src/ui/prompts/targetingPrompts.ts
  src/utils/prompts.ts
  src/utils/reportValidationErrors.ts
  src/utils/validators.ts
Labels: 5 min review

#200 fix: Handle displaying OR operator in targeting tree
  src/api/schemas.ts
  src/ui/prompts/listPrompts/filterListPrompt.ts
  src/ui/prompts/listPrompts/targetingListPrompt.ts
  src/ui/targetingTree.ts
Labels: 1 min review

#204 Release v4.6.0
  README.md
  docs/cleanup.md
  docs/diff.md
  docs/logout.md
  docs/org.md
  docs/status.md
  docs/usages.md
  oclif.manifest.json
  package.json
Labels: 5 min review

#203 chore: update description to explain definition and serve for targeting update
  docs/targeting.md
  oclif.manifest.json
  src/commands/targeting/update.ts
Labels: 1 min review

#205 lowercase the key input rather than throwing an error
  src/commands/createCommand.ts
  src/commands/updateCommand.ts
  src/commands/variations/update.test.ts
  src/commands/variations/update.ts
  src/ui/prompts/commonPrompts.ts
Labels: 1 min review

#207 Update readme to use in documentation
  DEVELOPMENT.md
  README.md
Labels: 1 min review, safe-changes

#206 feat: add tab completion
  README.md
  docs/autocomplete.md
  package.json
  yarn.lock
Labels: 1 min review

#202 chore: update prompt values color and heading
  src/commands/environments/update.ts
  src/commands/features/update.ts
  src/commands/targeting/__snapshots__/update.test.ts.snap
  src/commands/variables/update.ts
  src/commands/variations/update.ts
  src/ui/prompts/listPrompts/filterListPrompt.ts
  src/ui/prompts/listPrompts/listOptionsPrompt.ts
  src/ui/prompts/listPrompts/targetingListPrompt.ts
  src/ui/writer.ts
Labels: 5 min review

#208 chore: Add release step to update docs repo
  DEVELOPMENT.md
Labels: 1 min review, safe-changes

#211 chore: output targeting enable disable as a tree
  src/api/environments.ts
  src/commands/targeting/disable.ts
  src/commands/targeting/enable.ts
  src/ui/prompts/environmentPrompts.ts
  src/utils/targeting/index.ts
Labels: 5 min review

#210 Dvc 8076 refactor feature prompt
  src/commands/features/delete.ts
  src/commands/features/update.test.ts
  src/commands/features/update.ts
  src/commands/targeting/disable.ts
  src/commands/targeting/enable.ts
  src/commands/targeting/get.test.ts
  src/commands/targeting/get.ts
  src/commands/targeting/update.ts
  src/commands/variations/create.test.ts
  src/commands/variations/create.ts
  src/commands/variations/get.ts
  src/commands/variations/list.test.ts
  src/commands/variations/list.ts
  src/commands/variations/update.ts
  src/ui/prompts/featurePrompts.ts
  src/utils/targeting/index.ts
Labels: 10 min review

#213 Task: update the descriptions of various commands to include 'create'…
  README.md
  docs/features.md
  docs/projects.md
  docs/targeting.md
  docs/variables.md
  package.json
Labels: 5 min review

#214 chore: make targeting update command behave the same as other update commands
  docs/targeting.md
  docs/variations.md
  oclif.manifest.json
  src/commands/environments/update.ts
  src/commands/features/update.ts
  src/commands/targeting/update.test.ts
  src/commands/targeting/update.ts
  src/commands/updateCommand.ts
  src/commands/updateCommandWithCommonProperties.ts
  src/commands/variables/update.ts
  src/commands/variations/update.ts
  src/ui/prompts/listPrompts/filterListPrompt.ts
  src/ui/prompts/listPrompts/listOptionsPrompt.ts
  src/ui/prompts/listPrompts/targetingListPrompt.ts
  src/ui/prompts/listPrompts/variablesListPrompt.ts
  src/ui/prompts/targetingPrompts.ts
Labels: 10 min review

#215 chore: add features delete and list description
  docs/features.md
  oclif.manifest.json
  src/commands/features/delete.ts
  src/commands/features/list.ts
Labels: 1 min review

#212 chore: handle outputting in targeting tree audience match filters
  src/api/audiences.ts
  src/api/schemas.ts
  src/commands/targeting/disable.ts
  src/commands/targeting/enable.ts
  src/commands/targeting/get.test.ts
  src/commands/targeting/get.ts
  src/commands/targeting/update.test.ts
  src/commands/targeting/update.ts
  src/ui/prompts/listPrompts/filterListPrompt.ts
  src/ui/prompts/listPrompts/listOptionsPrompt.ts
  src/ui/prompts/listPrompts/targetingListPrompt.ts
  src/ui/targetingTree.ts
  src/utils/audiences/index.ts
  src/utils/audiences/utils.test.ts
Labels: 10 min review

#217 feat: support setting audienceMatch as a filter from list of existing audiences
  src/ui/prompts/listPrompts/filterListPrompt.ts
  src/ui/prompts/targetingPrompts.ts
Labels: 1 min review

#220 Release v4.6.1
  README.md
  docs/cleanup.md
  docs/diff.md
  docs/logout.md
  docs/org.md
  docs/status.md
  docs/usages.md
  package.json
Labels: 5 min review

#221 change headless sso to work properly
  src/commands/authCommand.ts
  src/commands/base.ts
  src/commands/environments/get.ts
  src/commands/environments/list.ts
  src/commands/environments/update.ts
  src/commands/features/create.ts
  src/commands/features/delete.ts
  src/commands/features/get.ts
  src/commands/features/list.ts
  src/commands/features/update.ts
  src/commands/generate/types.ts
  src/commands/keys/get.ts
  src/commands/login/sso.ts
  src/commands/targeting/disable.ts
  src/commands/targeting/enable.ts
  src/commands/targeting/get.ts
  src/commands/targeting/update.ts
  src/commands/variables/create.ts
  src/commands/variables/get.ts
  src/commands/variables/list.ts
  src/commands/variables/update.ts
  src/commands/variations/create.ts
  src/commands/variations/get.ts
  src/commands/variations/list.ts
  src/commands/variations/update.ts
  yarn.lock
Labels: 5 min review

#219 feat: add release yaml
  .github/actions/release/action.yml
  .github/actions/update-doc/action.yml
  .github/workflows/cli-release.yml
Labels: 5 min review

#223 chore: add input to release workflow
  .github/actions/release/action.yml
  .github/workflows/cli-release.yml
Labels: 1 min review

#229 chore: order env list by type in development, staging, production order
  README.md
  docs/generate.md
  oclif.manifest.json
  src/ui/prompts/environmentPrompts.ts
Labels: 1 min review

#230 feat: cache token to reuse if client id and secret match
  package.json
  src/api/clientCredentialsAuth.ts
  src/auth/ApiAuth.ts
  src/auth/TokenCache.ts
  src/auth/config.ts
  src/auth/getToken.ts
  src/commands/base.ts
  src/commands/generate/types.test.ts
  test/setup.ts
  yarn.lock
Labels: 5 min review

#231 allow keys flag to accept _ids
  src/commands/features/get.ts
Labels: 1 min review

#227 feat: improved design on auth page
  src/api/ssoAuth.ts
  src/ui/togglebot.ts
Labels: 5 min review

#233 Support IDs in environments --keys flag
  src/commands/environments/get.ts
Labels: 1 min review

#232 feat: add flag to usages to only list variable usages that arent a variable in the api
  docs/usages.md
  oclif.manifest.json
  src/commands/usages/__snapshots__/usages.test.ts.snap
  src/commands/usages/index.ts
  src/commands/usages/usages.test.ts
  test-utils/fixtures/usages/nodejs.js
Labels: 5 min review

#234 Dvc 8235 headless environments
  src/commands/environments/get.ts
Labels: 1 min review

#235 chore: Add TokenCache tests
  src/auth/ApiAuth.ts
  src/auth/TokenCache.test.ts
  src/auth/TokenCache.ts
  src/utils/fileSystem.ts
  test/setup.ts
Labels: 5 min review

#224 chore: add registry-url to set up node step
  .github/workflows/cli-release.yml
Labels: 1 min review

#236 chore: remove close button and auto close
  src/api/ssoAuth.ts
Labels: 1 min review

#222 chore: update release notes
  DEVELOPMENT.md
Labels: 1 min review, safe-changes

#237 feat: Use refresh token to fetch new token for sso auth
  oclif.manifest.json
  package.json
  src/auth/ApiAuth.ts
  src/auth/SSOAuth.ts
  src/auth/TokenCache.ts
  src/auth/config.ts
  src/auth/utils/getTokenExpiry.test.ts
  src/auth/utils/getTokenExpiry.ts
  src/auth/utils/getTokenPayload.test.ts
  src/auth/utils/getTokenPayload.ts
  src/auth/utils/index.ts
  src/auth/utils/shouldRefreshToken.test.ts
  src/auth/utils/shouldRefreshToken.ts
  src/commands/authCommand.ts
  src/commands/base.ts
  src/commands/login/sso.ts
  src/commands/repo/init.ts
Labels: 5 min review

#239 chore: update DEVELOPMENT.md
  DEVELOPMENT.md
Labels: 1 min review, safe-changes

#240 chore: add VS Code extension as possible caller
  src/commands/base.ts
Labels: 1 min review
