Repository DevCycleHQ/cli, pull requests merged in 2023-10, with the labels that each got.

#308 chore: add confirmation to features delete
  oclif.manifest.json
  src/commands/features/delete.ts
  src/ui/prompts/commonPrompts.ts
Labels: 1 min review

#307 Add includeFiles and excludeFiles to diff cmd
  docs/diff.md
  oclif.manifest.json
  src/commands/diff/index.ts
  src/commands/usages/index.ts
  src/types/configFile.ts
  src/utils/diff/diff.ts
  src/utils/getFilteredFiles.ts
Labels: 5 min review

#310 feat: add sortBy and sortOrder flags to projects get command
  docs/projects.md
  oclif.manifest.json
  src/api/projects.ts
  src/commands/getCommand.ts
  src/commands/projects/get.ts
Labels: 5 min review

#311 chore: made aliases for all list
  docs/environments.md
  docs/features.md
  docs/organizations.md
  docs/overrides.md
  docs/projects.md
  docs/variables.md
  docs/variations.md
  oclif.manifest.json
  src/commands/base.ts
  src/commands/environments/list.ts
  src/commands/features/list.ts
  src/commands/organizations/list.ts
  src/commands/overrides/list.ts
  src/commands/projects/list.ts
  src/commands/variables/list.ts
  src/commands/variations/list.ts
Labels: 10 min review

#306 fix: Only allow one refresh token request at a time
  src/auth/ApiAuth.test.ts
  src/auth/ApiAuth.ts
  src/auth/TokenCache.test.ts
  src/auth/TokenCache.ts
  src/utils/fileSystem.ts
Labels: 5 min review

#312 Add prompt to create targets when enable an environment
  src/commands/targeting/enable.ts
  src/commands/targeting/update.ts
  src/utils/features/quickCreateFeatureUtils.ts
  src/utils/targeting/index.ts
Labels: 5 min review

#309 Dvc 8568 variations update in variables create
  README.md
  docs/variables.md
  oclif.manifest.json
  src/api/zodClient.ts
  src/commands/variables/create.test.ts
  src/commands/variables/create.ts
  src/ui/prompts/listPrompts/variablesListPrompt.ts
Labels: 5 min review

#315 chore: dependabot
  .github/dependabot.yml
Labels: 1 min review

#330 chore: Remove watch lib
  docs/autocomplete.md
  docs/help.md
  package.json
  yarn.lock
Labels: 1 min review
