Repository DevCycleHQ/cli, pull requests merged in 2023-08, with the labels that each got.

#242 refactor!: Rename 'dvc org' to 'dvc organizations select'
  docs/org.md
  docs/organizations.md
  oclif.manifest.json
  src/commands/organizations/select.ts
Labels: 5 min review

#243 fix: Update outdated doc links
  README.md
Labels: 1 min review, safe-changes

#244 feat: Add 'organizations get' command
  docs/features.md
  docs/organizations.md
  oclif.manifest.json
  src/commands/features/get.ts
  src/commands/organizations/get.ts
Labels: 5 min review

#245 Fetch keys flags individually instead of filtering
  src/commands/environments/get.ts
  src/commands/features/get.ts
  src/commands/variables/get.ts
  src/utils/batchRequests.ts
Labels: 5 min review

#246 fix features get returning empty array when no keys
  README.md
  oclif.manifest.json
  src/commands/features/get.ts
Labels: 1 min review

#248 feat: dvc status return user email and Id
  src/commands/base.ts
  src/commands/status/index.ts
Labels: 1 min review

#249 chore: remove deprecated @types/axios package
  oclif.manifest.json
  package.json
  yarn.lock
Labels: 5 min review

#250 feat: Use org and project from repo config if it exists
  oclif.manifest.json
  src/auth/ApiAuth.ts
  src/auth/config.ts
  src/auth/utils/getOrgIdFromToken.test.ts
  src/auth/utils/getOrgIdFromToken.ts
  src/auth/utils/getTokenPayload.ts
  src/auth/utils/index.ts
  src/commands/alias/add.ts
  src/commands/base.ts
  src/commands/cleanup/index.ts
  src/commands/diff/index.ts
  src/commands/usages/index.ts
Labels: 5 min review

#251 fix: Check if repo config exists before reading file
  src/auth/config.ts
Labels: 1 min review

#252 chore: return valid JSON string from showError
  src/commands/variations/__snapshots__/create.test.ts.snap
  src/ui/writer.ts
Labels: 1 min review

#253 fix: Update org select command to require user auth
  src/commands/authCommand.ts
  src/commands/organizations/select.ts
Labels: 1 min review

#254 Prompt for variation values when updating feature variables
  src/api/zodClient.ts
  src/commands/features/__snapshots__/update.test.ts.snap
  src/commands/features/update.test.ts
  src/commands/features/update.ts
  src/ui/prompts/listPrompts/variablesListPrompt.ts
  src/ui/prompts/variablePrompts.ts
Labels: 5 min review

#255 update installation instructions to include homebrew
  README.md
Labels: 1 min review, safe-changes

#256 remove ability to change feature field in variables update command
  src/commands/variables/update.ts
Labels: 1 min review

#257 chore: Add build artifacts to release
  .github/actions/release/action.yml
  .gitignore
  docs/variables.md
  package.json
Labels: 5 min review

#258 chore: Add support for additional platforms
  .github/actions/build-artifacts/action.yml
  .github/actions/release/action.yml
  oclif.manifest.json
Labels: 5 min review

#259 fix: update devcycleClient names in BaseParser
  src/utils/parsers/BaseParser.ts
Labels: 1 min review

#260 fix: Pass all errors to oclif error handler after custom handling
  src/commands/base.ts
  src/commands/diff/diff.test.ts
  src/commands/features/create.test.ts
  src/commands/features/update.test.ts
  src/commands/targeting/get.test.ts
  src/commands/targeting/update.test.ts
  src/commands/variables/create.test.ts
  src/commands/variations/create.test.ts
  src/commands/variations/list.test.ts
  src/ui/writer.ts
Labels: 5 min review

#261 fix: Don't log error from oclif error handler
  src/commands/base.ts
Labels: 1 min review

#262 fix: Add more details to refresh token error
  src/auth/ApiAuth.ts
Labels: 1 min review

#263 fix: Return empty string when token refresh fails
  src/auth/ApiAuth.ts
Labels: 1 min review

#264 feat: Add pagination flags to variable list and get commands
  docs/variables.md
  oclif.manifest.json
  src/api/variables.ts
  src/commands/variables/get.test.ts
  src/commands/variables/get.ts
  src/commands/variables/list.test.ts
  src/commands/variables/list.ts
  src/commands/variations/create.ts
  src/ui/prompts/variablePrompts.ts
  src/ui/prompts/variationPrompts.ts
Labels: 5 min review

#267 fix: Use writer to log from ApiAuth
  src/auth/ApiAuth.ts
  src/commands/base.ts
Labels: 1 min review
